#os: Mac OS X

environment:
  myvar1: Hello, world!
  ANOTHER_VAR: Test!!!

install:
- echo "Should be run on both Windows and Mac"
- ENV
- ls
- sh: ls $HOME
- sh: echo "This is Bash script!"
- npm --version
- ps: 'Write-Host "This is run on Windows only: $env:USERPROFILE"'
- cmd: 'echo This run on Windows too: %USERPROFILE%'

build: off
test: off
