os: macosx

environment:
  myvar1: Hello, world!
  ANOTHER_VAR: Test!!!

install:
- ENV
- ls $HOME
- sh: echo "This is Bash script!"
- npm
- ps: This is run on Windows only!
- ps: This run on Windows too!
