os: Mac OS X

environment:
  myvar1: Hello, world!
  ANOTHER_VAR: Test!!!

install:
- echo "Should be run on both Windows and Mac"
- ENV
- ls
- ls $HOME
- sh: echo "This is Bash script!"
- npm
- ps: This is run on Windows only!
- cmd: This run on Windows too!
